{"name": "Ошибка при неверном логине", "status": "passed", "start": 1751895412352, "stop": 1751895412922, "uuid": "111ad6c2-a3f1-4303-b92c-7656e353f010", "historyId": "5bf8f550dc17080d3f120eb4e949e80e", "testCaseId": "5bf8f550dc17080d3f120eb4e949e80e", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_wrong_login", "labels": [{"name": "feature", "value": "Логин курьера"}, {"name": "epic", "value": "Курьеры"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-3L4TMJM"}, {"name": "thread", "value": "25140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}